<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Final_Project_Razor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\ModelRecipes\RetrieveAll\**" />
    <Content Remove="Pages\ModelRecipes\RetrieveAll\**" />
    <EmbeddedResource Remove="Pages\ModelRecipes\RetrieveAll\**" />
    <None Remove="Pages\ModelRecipes\RetrieveAll\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Pages\ModelComments\RetrieveById.cs" />
    <Compile Remove="Pages\ModelFavorites\RetrieveAll.cshtml.cs" />
    <Compile Remove="Pages\ModelRecipes\Created.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Pages\ModelComments\RetrieveCommentsByRecipeId.cshtml" />
    <Content Remove="Pages\ModelFavorites\RetrieveAll.cshtml" />
    <Content Remove="Pages\ModelFavorites\RetrieveFavoritesByUserId.cshtml" />
    <Content Remove="Pages\ModelRatings\Update.cshtml" />
    <Content Remove="Pages\ModelUsers\Management.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Pages\ModelRecipes\RetrieveAll.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Final Project\Models\Models.csproj" />
    <ProjectReference Include="..\..\Final Project\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\ModelComments\RetrieveCommentsByRecipeId.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\ModelRatings\Update.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\ModelUsers\Management.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\ModelComments\RetrieveCommentsByRecipeId.cshtml" />
    <None Include="Pages\Management.cshtml" />
    <None Include="Pages\ModelRatings\Update.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\ModelUsers\Management.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\ModelRatings\Update.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\ModelComments\RetrieveCommentsByRecipeId.cshtml" />
  </ItemGroup>

</Project>
